version: '3.8'

services:
  arangodb:
    image: arangodb:latest
    container_name: arangodb
    restart: always
    environment:
      - ARANGO_ROOT_PASSWORD=track_planner
    ports:
      - '8529:8529'
    volumes:
      - arangodb_data:/var/lib/arangodb3

volumes:
  arangodb_data:
